In [1]:
import numpy as np

# Lista de Exercícios 02 - Numpy

#### 01 - Análise de Regressão - Erro quadrático médio

$EQM = \frac{1}{n}\sum_{i=1}^{n}(y_{prediction} - y_{i})^2$.

In [7]:
def calculate_eqm(prediction, real):
    return (1/prediction.size)*((prediction - real)**2).sum()

In [8]:
y_prediction = np.array([1, 2, 3])
y_i = np.array([0, 0, 3])
calculate_eqm(y_prediction, y_i)

1.6666666666666665

#### 02 - Eletroencefalografia

$X_{e,i} = \hat{X_{e,i}} - \frac{1}{N}\sum_{e=1}^{N}\hat{X_{e,i}}$

In [34]:
def process_EEG_signal(signal):
    N = signal.shape[0] # pegando o número de linhas da matriz original

    return (signal - (1/N * (N * signal)))

Sinceramente, essa é a parte em que eu me confundo, porque como eu não tenho uma base estatística, eu não sei como implementar para a aplicação de matrizes a parte do somatório.

O somatório de N é igual a 64, que é o total de linhas da matriz; ou se N é igual a 2145, que é a soma de cada número até chegar a 64 (1+2+3+4...+64=2145). 

In [45]:
signal = np.random.randn(64, 512)
modified_signal = process_EEG_signal(signal)
modified_signal


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [44]:
print(f'''Matriz Sinal Original - {signal.shape}
Matriz Sinal Modificado - {modified_signal.shape}''')

Matriz Sinal Original - (64, 512)
Matriz Sinal Modificado - (64, 512)


In [46]:
(modified_signal - signal).sum()

64.80126079665865

#### 03 - Outlier - Distância Interquartil

In [111]:
def locate_outlier(data):
    Q1 = np.quantile(data, 0.25)
    Q3 = np.quantile(data, 0.75)
    IQR = Q3 - Q1
    out_down = 1.5 * IQR - Q1
    out_up = 1.5 * IQR + Q3
    
    outliers = np.concatenate((data[data < out_down], data[data > out_up]))
    outliers_count = outliers.size 
    is_outlier = np.isin(data, outliers)

    return is_outlier, outliers_count, outliers

In [118]:
data = np.random.randn(300, 15)
is_outlier, outliers_count, outliers = locate_outlier(data)

In [119]:
is_outlier

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

In [120]:
outliers_count

4498

In [121]:
outliers

array([2.33258755, 0.79061142, 0.31061769, ..., 2.89463782, 3.9724908 ,
       2.96543581])